main: net.electronexchange.minemath.MineMath
name: MineMath
version: 1.0.0
author: bcbwilla
website: electronexchange.net
description: MineMath provides basic math functionality (pun intended) from the chat terminal.
commands:
    calculate:
        description: does basic arithmetic
        usage: /<command> [expression]
        aliases: calc
    integrate:
        description: approximates integral of function integrated from lower to upper limit
        usage: /<command> [function] [variable] [lower limit] [upper limit]
        aliases: int
    derivative:
        description: approximates derivative of a function at a given position
        usage: /<command> [function] [variable] [position]
        aliases: der
    minemath:
        description: info
        useage: /<command> [option]
        aliases: mm
    variable:
        description: sets of prints the value of a variable
        usage: /<command> set [variable] [value] or /<command> echo [variable]
        aliases: var