main: net.electronexchange.minemath.MineMath
name: MineMath
version: 1.0
author: bcbwilla
description: Math stuff
commands:
    calc:
        description: does basic arithmetic
        useage: /<command> [expression]
    integrate:
        description: approximates integral between lower and upper limit
        useage: /<command> [function] [variable] [lower limit] [upper limit]
    derivative:
        description: approximates function at a given position
        useage: /<derivative> [function] [variable] [position]
    math:
        description: just a test command
        useage: /<command>
    setvar:
        description: sets the value of a variable.  if the variable is new, it creates it.
        useage: /<command> [variable] [value]
